#configurations serving
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federated.configurations.serving.knative.dev
spec:
  group: federated.serving.knative.io
  names:
    kind: Configuration
    plural: configurations
  scope: Namespaced
  version: v1alpha1
---
# revisions.serving
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federated.revisions.serving.knative.dev
spec:
  group: federated.serving.knative.io
  names:
    kind: Revision
    plural: revisions
  scope: Namespaced
  version: v1alpha1
---
# routes.serving
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federated.routes.serving.knative.dev
spec:
  group: federated.serving.knative.io
  names:
    kind: Route
    plural: routes
  scope: Namespaced
  version: v1alpha1
---
# services.serving
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federated.services.serving.knative.dev
spec:
  group: federated.serving.knative.io
  names:
    kind: Service
    plural: services
  scope: Namespaced
  version: v1alpha1
---
# services.serving
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federated.builds.build.knative.dev
spec:
  group: federated.build.knative.dev
  names:
    kind: Build
    plural: builds
  scope: Namespaced
  version: v1alpha1
---
# services.serving
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federated.buildtemplates.build.knative.dev
spec:
  group: federated.build.knative.dev
  names:
    kind: BuildTemplate
    plural: buildtemplates
  scope: Namespaced
  version: v1alpha1