apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: services.serving.knative.dev
  namespace: federation-system
spec:
  target:
    version: v1alpha1
    kind: Service
  namespaced: true
  comparisonField: Generation
  propagationEnabled: true
  template:
    group: federation.knative.dev
    version: v1alpha1
    kind: FederatedService
  placement:
    kind: FederatedServicePlacement
